### ISSUE TITLE
Error executing callback ui_tabs_callback

### ISSUE THREAD

**Issue by jeguepowerr** [diffus-me/sd-webui-facefusion#1]
![image](https://github.com/diffus-me/sd-webui-facefusion/assets/112975569/d60bd88d-6ea0-4ded-ad13-af1a21c7fbd4)
Can someone help me, please.

**Comment by linjiX** [comment]
@jeguepowerr 
It is fixed in 01e624d09bd17f5fe37cbc199244b5dad5a52d31, you pull the latest version and try again.
