### ISSUE TITLE
FFMpeg is not installed

### ISSUE THREAD

**Issue by Methelina** [diffus-me/sd-webui-facefusion#15]
I have an error **[FACEFUSION.CORE] FFMpeg is not installed** 
And i can't find a way to fix it. 
![image 2](https://media.discordapp.net/attachments/1085777362014191676/1180403792018161664/image.png?ex=657d4bb2&is=656ad6b2&hm=a806433253c1d80b4c30734a939b8bf44c3fa3c4a61ebf9dd36a833dacde4b9d&=&format=webp&quality=lossless&width=1041&height=657)

in same way 
```
(venv) O:\Software\_AI\SD_XPuCT\venv\Scripts>python -c "import imageio_ffmpeg; print(imageio_ffmpeg.__version__)"
0.4.9
```
![image 3](https://media.discordapp.net/attachments/1085777362014191676/1180403792601153598/image.png?ex=657d4bb2&is=656ad6b2&hm=d6c72f3caa26c94ec52f7a2b6bdd6ecf73b25fe1afeeca3cedf441985fff6776&=&format=webp&quality=lossless)
**And checking the FFmpeg installation returns the version:**

![image 4](https://cdn.discordapp.com/attachments/1085777362014191676/1180403792336932914/image.png?ex=657d4bb2&is=656ad6b2&hm=9321dd5bb9ec517ba8a9b20539ba6300dcdec2ac66af52fd78997147c39853a6&)
---
And the environment var is still on the place
![image 1](https://github.com/diffus-me/sd-webui-facefusion/assets/3624475/0f2e9544-b0d0-4cd6-8922-8361e95defd5)

---
And here the error:
![image 5](https://cdn.discordapp.com/attachments/1085777362014191676/1180403791690989619/image.png?ex=657d4bb2&is=656ad6b2&hm=e440ead51bc0c3ec4e8027d2fc25fb965bf8d5924422029c479a2ef45a24408e&)

**Comment by johnwayne087** [comment]
I used the command in powershell `winget install ffmpeg`. I restarted my shell and that fixed the issue.

**Comment by Methelina** [comment]
> I used the command in powershell `winget install ffmpeg`. I restarted my shell and that fixed the issue.
Saddely it does nothing cuz the FFMpeg is already installed as u can see in my previous post and presented in the env var of the system :( I installed it manualy in the .env of the extension and it still told me that "FFMPEG is not installed"

**Comment by ghzgod** [comment]
Run `winget install -e --id Gyan.FFmpeg` and then reboot your windows machine.

Source: https://docs.facefusion.io/installation/platform/windows

**Comment by Methelina** [comment]
> Run `winget install -e --id Gyan.FFmpeg` and then reboot your windows machine.
> 
> Source: https://docs.facefusion.io/installation/platform/windows

Thx, but facefusion was installed properly as you can see on the screenshots from first message at the beginning :(

**Comment by Methelina** [comment]
Fixed at last!!!

The problem was the absence of the linking to ffmpeg from win env to the **virtual enviroment of python** in the Stable Diffusion:
`webui-user.bat`

the env was at default:
`
set PATH=git\cmd
`

and need to be changed to: 
`
set PATH=%PATH%;git\cmd;python;venv\scripts;ffmpeg;venv\Lib\site-packages\torch\lib
`
After that the ffmpeg will be linked properly to SD  and loaded with Face Fusion. Hope it will helps to ppl with same problem i encountered.
