### ISSUE TITLE
Some constructive feedback (I hope). :)

### ISSUE THREAD

**Issue by Ainaemaet** [diffus-me/sd-webui-facefusion#6]
An opinion piece, but hear me out please. It's a cool little program you got here, but do you really think the "lock down the tools" so people can't use them as they want is the right way to go, rather than putting the focus on encouraging ethical use?

In the last 4 decades I've been around I've seen time & time again that this only causes more issues than it helps; & while it is, of course, up to you to decide how you will develop your product I can't see it gaining much traffic over inevitable competitors who don't treat adults like children. 

Essentially all you have done is _guarantee_ there will be unlocked versions of your software; & it will almost certainly just be superseded by something that allows people to make what they want, because people don't enjoy being handled like babies who can't play nice together (even if that is sometimes the case, the large majority of people wouldn't misuse it - & those who would **will find a way anyhow**).

It makes sense for Adobe, or Microsoft (& even many of these bigger companies are trying to find ways to prevent _**harmful**_  misuse _while still allowing nudity_; because you know, nudity is a REAL thing that is a fact of life, & both nudity & _ethical_ pornography are **completely legal** & in no way something that should be shamed. 
Erotic art is an entirely ethical use of software & a natural part of human life & attempts to prevent it from happening don't lead to good places. Time for the world to "Grow Up". 

If people misuse a tool, it is on THEM & though I understand completely the desire to help ensure safety, things like SynthID & Adobe CRedentials are the right way to do it, not hobbling your product so that even mature & consenting adults can't use it as they see fit. 

Best of luck with your software & much respect to all involved.

**Comment by linjiX** [comment]
This extension is ported from [FaceFusion](https://github.com/facefusion/facefusion). I just made it to a webui extension. The NSFW check is from the original repo. I will not remove the check unless it is removed from the original repo. It is respect for the original author.

**Comment by henryruhs** [comment]
@linjiX you have my respect :-)
