### ISSUE TITLE
 automatic1111 extension does not work, not appears as a tab

### ISSUE THREAD

**Issue by ivaxsirc** [diffus-me/sd-webui-facefusion#7]
When loading appears:
tried  now Warning: Failed to install 'tqdm>=4.66.1', some preprocessors may not work.
and
FACEFUSION.CORE] FFMpeg is not installed

Thanks

**Comment by ltm920716** [comment]
try `apt install ffmpeg` and reload UI

**Comment by linjiX** [comment]
- About `tqdm`:
`tqdm` is in the `requirements.txt`, it should be installed automatically. Could you paste the related log about why the installation is failed. Also you can try to install it manually in your webui venv.
- About `ffmpeg`:
As @ltm920716 said, `ffmpeg` should be installed manually.

**Comment by ivaxsirc** [comment]
> * About `tqdm`:
>   `tqdm` is in the `requirements.txt`, it should be installed automatically. Could you paste the related log about why the installation is failed. Also you can try to install it manually in your webui venv.
> * About `ffmpeg`:
>   As @ltm920716 said, `ffmpeg` should be installed manually.

thks for your answer
I tried with stability matrix without any extension all cleaned

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.0
Commit hash: <none>
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
O:\stability\matrix\Packages\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension O:\stability\matrix\Packages\stable-diffusion-webui\extensions\sd-webui-facefusion.
Launching Web UI with arguments: --xformers --api --skip-torch-cuda-test --skip-python-version-check
*** Command: "O:\stability\matrix\Packages\stable-diffusion-webui\venv\Scripts\python.exe" "O:\stability\matrix\Packages\stable-diffusion-webui\extensions\sd-webui-facefusion\install.py"
*** Error code: 1
*** stdout: Installing None
*** 
*** stderr: O:\stability\matrix\Packages\stable-diffusion-webui\extensions\sd-webui-facefusion\install.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "O:\stability\matrix\Packages\stable-diffusion-webui\extensions\sd-webui-facefusion\install.py", line 26, in <module>
***     launch.run_pip("install 'onnxruntime-gpu>=1.16.0'")
***   File "O:\stability\matrix\Packages\stable-diffusion-webui\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "O:\stability\matrix\Packages\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install None.
*** Command: "O:\stability\matrix\Packages\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install 'onnxruntime-gpu>=1.16.0' --prefer-binary
*** Error code: 1
*** stderr: ERROR: Invalid requirement: "'onnxruntime-gpu"
*** 
*** Error loading script: facefusion_ui.py
    Traceback (most recent call last):
      File "O:\stability\matrix\Packages\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "O:\stability\matrix\Packages\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "O:\stability\matrix\Packages\stable-diffusion-webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 6, in <module>
        from facefusion.core import apply_args, get_argument_parser, limit_resources, pre_check
      File "O:\stability\matrix\Packages\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\core.py", line 11, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

---
Loading weights [6ce0161689] from O:\stability\matrix\Packages\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: O:\stability\matrix\Packages\stable-diffusion-webui\configs\v1-inference.yaml
Startup time: 19.0s (prepare environment: 14.7s, initialize shared: 0.2s, other imports: 1.5s, setup codeformer: 0.1s, load scripts: 1.7s, create ui: 0.5s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
Model loaded in 3.4s (load weights from disk: 0.6s, create model: 0.4s, apply weights to model: 2.1s, calculate empty prompt: 0.1s).

**Comment by ivaxsirc** [comment]
> apt install ffmpeg

i'm in windows not in linux
how can i do in windows, i tried with pip but it doesn't work
thanks

**Comment by linjiX** [comment]
@ivaxsirc You can also find the Windows installation guide in the [documation](https://docs.facefusion.io/installation/platform/windows#ffmpeg) from the FaceFusion original repo.

The `tqdm` and other dependencies installation issue should be fixed in 282165a789cfe354e5f9d4661e24fa10e68592b8, please pull the latest code and try it again.
